In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("SalaryData_Train.csv")

In [3]:
data

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
dataz=pd.read_csv("SalaryData_Test.csv")

In [5]:
dataz

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [7]:
convert = {' >50K': 1, ' <=50K': 2}
dataz = dataz.replace({'Salary': convert})

In [10]:
convert = {' >50K': 1, ' <=50K': 2}
dataz = dataz.replace({'Salary': convert})

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

columns=["workclass","education","maritalstatus","occupation","relationship","race","sex","native"]

In [12]:
for i in columns:
    dataz[i]= label_encoder.fit_transform(dataz[i])
    

In [13]:
dataz

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37       2  
1          37       2  
2          37       1  
3          37       1  
4          37       2  
...       ...     ...  
15055      37       2  
15056      37       2  
15057      37       2  
15058      37       2  
15059      37       1  

[15060 rows x 14 columns]

In [15]:
convert = {' >50K': 1, ' <=50K': 2}
data = data.replace({'Salary': convert})

In [16]:
convert = {' >50K': 1, ' <=50K': 2}
data = data.replace({'Salary': convert})

In [17]:
for i in columns:
    data[i]= label_encoder.fit_transform(data[i])

In [18]:
data

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37       2  
1          37       2  
2          37       2  
3          37       2  
4           4       2  
...       ...     ...  
30156      37       2  
30157      37       1  
30158      37       2  
30159      37       2  
30160      37       1  

[30161 rows x 14 columns]

### Performing Naive Bayes Algorithm with differnet Models(conditions)¶

In [19]:
x_train = data.iloc[:,0:13]
y_train = data.iloc[:,13]
x_test = dataz.iloc[:,0:13]
y_test = dataz.iloc[:,13]

#### GaussianNB

GaussianNB implements the Gaussian Naive Bayes algorithm for classification.

In [20]:
from sklearn.naive_bayes import GaussianNB
clsfrgnb = GaussianNB()

In [21]:
model1=clsfrgnb.fit(x_train, y_train)

In [22]:
y_pred_gnb = model1.predict(x_test)

In [23]:
y_pred_gnb

array([2, 2, 2, ..., 2, 1, 2], dtype=int64)

In [24]:
print ("Accuracy",np.mean(y_pred_gnb==y_test.values.flatten())*100)

Accuracy 79.46879150066401


In [25]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_gnb)

array([[ 1209,  2491],
       [  601, 10759]], dtype=int64)

In [26]:
pd.crosstab(y_test.values.flatten(),clsfrgnb)

col_0  GaussianNB()
row_0              
1              3700
2             11360

#### MultinomialNB

MultinomialNB implements the naive Bayes algorithm for multinomially distributed data, and is one of the two classic naive Bayes variants used in text classification (where the data are typically represented as word vector counts, although tf-idf vectors are also known to work well in practice).

In [27]:
from sklearn.naive_bayes import MultinomialNB
clsfrmnnb = MultinomialNB()   # clsfrgnb = claasification with Multinominal Naive Bayes

In [28]:
model2=clsfrmnnb.fit(x_train, y_train)
model2

MultinomialNB()

In [29]:
y_pred_mnnb = model2.predict(x_test)  

In [30]:
confusion_matrix(y_test, y_pred_mnnb)

array([[  780,  2920],
       [  469, 10891]], dtype=int64)

In [31]:
pd.crosstab(y_test.values.flatten(),clsfrmnnb)

col_0  MultinomialNB()
row_0                 
1                 3700
2                11360

In [33]:
print ("Accuracy",np.mean(y_pred_mnnb==y_test.values.flatten()))

Accuracy 0.7749667994687915


In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_mnnb)*100

77.49667994687915

In [36]:
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import CategoricalNB

#### ComplementNB

ComplementNB implements the complement naive Bayes (CNB) algorithm

In [51]:
clsfrCLnb = ComplementNB()

In [52]:
model3=clsfrCLnb.fit(x_train, y_train)

In [53]:
y_pred_CLnb = model3.predict(x_test) 

In [54]:
confusion_matrix(y_test, y_pred_CLnb)

array([[  780,  2920],
       [  469, 10891]], dtype=int64)

In [55]:
pd.crosstab(y_test.values.flatten(),clsfrCLnb)

col_0  ComplementNB()
row_0                
1                3700
2               11360

In [56]:
print ("Accuracy",np.mean(y_pred_CLnb==y_test.values.flatten()))

Accuracy 0.7749667994687915


### 4 BernoulliNB

#### BernoulliNB implements the naive Bayes training and classification algorithms

In [57]:
clsfrBnb = BernoulliNB()

In [58]:
model4=clsfrBnb.fit(x_train, y_train)

In [59]:
y_pred_Bnb = model4.predict(x_test) 

In [60]:
confusion_matrix(y_test, y_pred_Bnb)

array([[2690, 1010],
       [3080, 8280]], dtype=int64)

In [61]:
print ("Accuracy",np.mean(y_pred_Bnb==y_test.values.flatten())*100)

Accuracy 72.84196547144755


### CategoricalNB

#### CategoricalNB implements the categorical naive Bayes algorithm for categorically distributed data

In [62]:
clsfrCALnb = CategoricalNB()

In [63]:
model4=clsfrCALnb.fit(x_train, y_train)

In [64]:
model4=clsfrCALnb.fit(x_train, y_train)

In [ ]:
confusion_matrix(y_test, y_pred_CALnb)

In [ ]:
print ("Accuracy",np.mean(y_pred_CALnb==y_test.values.flatten())*100)

Accuracy 85.66401062416999

In [67]:
seed = 7
models = []
models.append(('GNB', GaussianNB()))
models.append(('MNB', MultinomialNB()))
models.append(('CPTNB', ComplementNB()))
models.append(('CATNB', CategoricalNB()))
models.append(('BALNB', BernoulliNB()))


In [68]:
results = []
names = []
scoring = 'accuracy'

In [69]:
import warnings
warnings.filterwarnings('ignore')

In [70]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

for name, model in models:
    kfold = KFold(n_splits=10, random_state=seed,shuffle = True)
    cv_results = cross_val_score(model, x_train, y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

GNB: 0.795498 (0.007394)
MNB: 0.772919 (0.008042)
CPTNB: 0.772919 (0.008042)
CATNB: nan (nan)
BALNB: 0.725573 (0.005228)
